server:
  port: 8002

spring:
  cloud: 
    config: 
      server: 
        native: 
          search-locations: classpath:/shared
  application:
    name: config
  profiles:
    active: native
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
