eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8003
spring:
  application:
    name: service-zuul
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: eureka-client-hello-a
#    api-b:
#      path: /api-b/**
#      serviceId: eureka-client-hello-b